:toc:
:toc-title:
:toclevels: 2
:sectnums:
= AsyncAPI-UI

== Quickstart

. Start Kafka components:
+
----
./cluster-setup.sh
----

. Start KafkaApplication locally.
. Publish test data:
+
----
./test-data.sh
----

. Compile and start the UI:
+
----
cd ./asyncapi-ui
npm install
npm install --save @asyncapi/react-component@next
ng serve
----

. Navigate to localhost:4200.


== Defining AsyncAPIs
=== Custom extensions

Nearly every object within an AsyncAPI definition can be extended with specification extensions:

* https://www.asyncapi.com/docs/specifications/v2.0.0#specificationExtensions
* "x-" prefix for new fields
* the custom fields are currently not rendered by the React component!

=== Defining Kafka-specific properties with AsyncAPI
*Server Configuration* +
It is currently not possible to configure the Kafka Broker with Kafka-specific
bindings within an AsyncAPI definition. Kafka Topics are equivalent to AsyncAPI
Channels. Therefore, the channel names correspond to the Kafka topic names.
Additional properties, e.g. the number of partitions or replication factors, could be configured by using custom extensions like described in paragraph 3.1.

*Message Binding* +
The "bindings" property of the https://www.asyncapi.com/docs/specifications/v2.0.0#messageObject[message object] can be used to define keys of Kafka messages.
Further details are provided https://github.com/asyncapi/bindings/tree/master/kafka[here].
Since "key" is defined to be a https://www.asyncapi.com/docs/specifications/v2.0.0#schemaObject[Schema Object], various additional properties can be specified and referenced.

*Operation Binding* +
The "bindings" property can also be applied to the https://www.asyncapi.com/docs/specifications/v2.0.0#operationObject[operation object].
It can be used to define the _groupId_ and the _clientId_ of the consumer/producer.
Since _groupId_ and _clientId_ are as well defined as https://www.asyncapi.com/docs/specifications/v2.0.0#schemaObject[Schema Objects], they could also be more complex than simple strings.


== Official Extensions and Functionalities in Development
=== Diff library

The diff library is in an early stage of development and aims to enable comparison and compatibility of API changes.

* https://github.com/asyncapi/diff

=== AsyncAPI Studio

Studio is currently in an early stage of development and wants to offer an editor (similar to the playground) and potentially some other functionalities (?).

* https://github.com/asyncapi/studio

=== Modelina

As well in an early stage of development.
Did not reach version 1.0.0 yet and therefore, breaking changes  are still possible.
Modelina SDK wants to enable generation of data models from JSON and AsyncAPI definitions.

* https://github.com/asyncapi/modelina
* seems to only support JavaScript as output language (?)
